**You work in ABC Corporation as a Data Analyst.**

**Your corporation has told you to use the numpy package and do some tasks related to that**

- Tasks to be performed

- 1. Create a 3x3 matrix array with values ranging from 2 to 10.

In [1]:
import numpy as np

In [3]:
arr = np.array([[2,3,6],[7,4,8],[1,3,9]])

In [4]:
arr

array([[2, 3, 6],
       [7, 4, 8],
       [1, 3, 9]])

In [5]:
arr.shape

(3, 3)

- 2. Create a numpy array having user input values and convert the integer type to
  the float type of the elements of the array. 
 
- For instance:

**Original array [1, 2, 3, 4]**


**Array converted to a float type: [ 1. 2. 3. 4.]**

In [20]:
my_array = []
for i in range(5):
    int_arr = int(input('enter elements:'))
    my_array.append(int_arr)
new = np.array(my_array)
print(new)

enter elements:45
enter elements:67
enter elements:23
enter elements:78
enter elements:12
[45 67 23 78 12]


In [21]:
# my_array.astype(float)
type(new)

numpy.ndarray

In [22]:
new1 = [float(i) for i in new]  

In [23]:
new1

[45.0, 67.0, 23.0, 78.0, 12.0]

- 3. Write a Numpy program to append values to the end of an array.

- For instance:

**Original array: [10, 20, 30]**

**After append values to the end of the array: [10 20 30 40 50 60 70 80 90]**

In [13]:
s1 = np.array([10,20,30])

In [14]:
s1

array([10, 20, 30])

In [29]:
s2 = np.append(s1,[40,50,60,70,80,90])

In [30]:
s2

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [31]:
type(s2)

numpy.ndarray

- 4. Create two numpy arrays and add the elements of both the arrays and store the
  result in sumArray.

In [34]:
n1 = np.array([4,7,9])
n2 = np.array([8,2,6])

In [36]:
sumArray = n1 + n2

In [37]:
sumArray

array([12,  9, 15])

- **5. Create a 3*3 array having values from 10-90(interval of 10) and store that in
  array1.**
  
  
**Perform the following tasks:**

- **a. Extract the 1st row from the array.**
- **b. Extract the last element from the array.**

In [45]:
array1 = np.arange(10,100,10)

In [46]:
array1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
array1 = array1.reshape(3,3)

In [49]:
array1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [51]:
array1[0]
#extract 1st row from array

array([10, 20, 30])

In [52]:
#extract last element in array
array1[2,2]

90